# Generated by Django 5.0.6 on 2024-07-21 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="user_auth_u_email_7376d6_idx")
                ],
            },
        ),
    ]
