# Generated by Django 5.0.6 on 2024-07-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="unknown", max_length=40),
        ),
    ]
